objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of any Promissor account</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Launch</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Candidate__c.object
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of this contact for the organization</description>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Exam__c.object
<CustomObject>
    <label>Exam</label>
    <nameField>
        <displayFormat>Exam - {00000}</displayFormat>
        <label>Exam ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{MM}-{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Case_HandlerTest.cls
@isTest
public class Case_HandlerTest {

    static testMethod void BeforeInsertTest(){
        
        Exam__c e = TestUtil.createExam(true);
        Candidate__c candidate = TestUtil.createCandidate(true);
        
        Registration__c r = TestUtil.createdRegistration( false );
        r.Exam__c = e.Id;
        r.Candidate__c = candidate.Id;
        insert r;
        
        Case c = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Missing results').getRecordTypeId());
        c.Registration_id__c = r.Id;
        
        insert c;
        
        system.assert( [select Evt_folder_name__c from Case where Id = :c.Id].Evt_folder_name__c != null );
        
    }
    
    static testMethod void BeforeUpdateTest(){
        
        Exam__c e = TestUtil.createExam(true);
        Candidate__c candidate = TestUtil.createCandidate(true);
        
        Registration__c r = TestUtil.createdRegistration( false );
        r.Exam__c = e.Id;
        r.Candidate__c = candidate.Id;
        insert r;
        
        Registration__c r1 = TestUtil.createdRegistration( false );
        r1.Exam__c = e.Id;
        r1.Candidate__c = candidate.Id;
        insert r1;
        
        Case c = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        c.Registration_id__c = r.Id;
        c.Status = 'Closed';
        insert c;
		
		c.Original_Record_Type__c = 'Missing results';  
        c.Registration_id__c = r1.Id;
        update c;
        
        system.assert( [select Evt_folder_name__c from Case where Id = :c.Id].Evt_folder_name__c != null );
        
    }
    
    static testMethod void AfterUpdateTest(){
        
        Exam__c e = TestUtil.createExam(true);
        Candidate__c candidate = TestUtil.createCandidate(true);
        
        Registration__c r = TestUtil.createdRegistration( false );
        r.Exam__c = e.Id;
        r.Candidate__c = candidate.Id;
        insert r;
        
        Registration__c r1 = TestUtil.createdRegistration( false );
        r1.Exam__c = e.Id;
        r1.Candidate__c = candidate.Id;
        insert r1;
        
        Case parent = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        parent.Registration_id__c = r.Id;
        parent.Status = 'Closed';
        insert parent;
        
        executioncontrol.afternInserthasrun = false;
        
        Case c = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        c.Registration_id__c = r.Id;
        c.Status = 'Closed';
        insert c;
		
        executioncontrol.afternInserthasrun = false;
        
		c.Original_Record_Type__c = 'Missing results';  
        c.Registration_id__c = r1.Id;
        c.parentId = parent.Id;
        update c;
        
        system.assert( [select Evt_folder_name__c from Case where Id = :c.Id].Evt_folder_name__c != null );
        
    }
    
    static testMethod void AfterInsertTest(){
        Account a = TestUtil.createAccount();
        insert a;
        
        Contact cont = testUtil.createContact(false, a);
        cont.Status__c = 'Active';
        insert cont;
        
        Exam__c e = TestUtil.createExam(true);
        Candidate__c candidate = TestUtil.createCandidate(true);
        
        Registration__c r = TestUtil.createdRegistration( false );
        r.Exam__c = e.Id;
        r.Candidate__c = candidate.Id;
        insert r;
        
        Registration__c r1 = TestUtil.createdRegistration( false );
        r1.Exam__c = e.Id;
        r1.Candidate__c = candidate.Id;
        insert r1;
        
        Case parent = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        parent.Registration_id__c = r.Id;
        insert parent;
        
        executioncontrol.afternInserthasrun = false;
        
        Test.startTest();
        
        Case c = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        c.Registration_id__c = r.Id;
        c.parentId = parent.Id;
        c.Status = 'Closed';
        c.AccountId = a.Id;
        insert c;
		
        Test.stopTest();
        
    }
}