objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>CCID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Client Candidate ID</description>
        <externalId>true</externalId>
        <label>CCID</label>
        <length>30</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTS_Candidate_ID__c</fullName>
        <externalId>true</externalId>
        <label>VTS candidate ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Exam_Name__c</fullName>
        <label>Exam Name</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Exam_Series_Code__c</fullName>
        <label>Exam Series Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTS_Exam_ID__c</fullName>
        <externalId>true</externalId>
        <label>VTS Exam ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Exam</label>
    <nameField>
        <displayFormat>Exam - {00000}</displayFormat>
        <label>Exam ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Integration_Object_Collection.cls
public with sharing class Integration_Object_Collection {

	public Exam__c exam{get;set;}
	public Candidate__c candidate{get;set;}
	public Account  TestCenter{get;set;}
	
	public Integration_Object_Collection(VTS_Registration record){
		
		this.Exam = new Exam__c(VTS_Exam_ID__c = record.exam.id, Exam_Name__c = record.exam.name, 
									Exam_Series_code__c = record.exam.code);
									
		this.Candidate = new Candidate__c(VTS_Candidate_ID__c = record.candidate.Id, CCID__c = record.candidate.clientCandidateId,
											First_Name__c = Record.Candidate.firstname, 
											Last_name__c = record.Candidate.lastname);
		


		this.TestCenter = new Account();									
	}


}