objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Account is not a Client.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Account is not a Client.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exams</relationshipLabel>
        <relationshipName>Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <displayFormat>Exam - {00000}</displayFormat>
        <label>Exam ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test center</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{MM}-{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DetailPageTest.cls
@isTest
public class DetailPageTest {
    public static testmethod void detailPageTest()
    {
        Account a = TestUtil.createAccount();
        a.RecordTypeId=[select id from recordtype where name='Client' limit 1].id;
        a.VTS_Client_id__c = 12345;
        insert a;
        
        
        Account testc=TestUtil.createTestCenterAccount(true, 8484);
        Exam__c e = TestUtil.createExam(true);
        e.Client__c=a.id;
        update e;
        Candidate__c candidate = TestUtil.createCandidate(true);
        
        Registration__c r = TestUtil.createdRegistration( false );
        r.Exam__c = e.Id;
        r.Candidate__c = candidate.Id;
        r.Test_Center__c=testc.id;
        
        insert r;
        
        Case c = TestUtil.createCase(false, schema.SObjectType.Case.GetrecordtypeinfosbyName().get('Request to reschedule').getRecordTypeId());
        c.Registration_id__c = r.Id;
        insert c;

        DetailsPage dp=new DetailsPage();
        System.assertNotEquals(Null, dp.MytestCenter);
        System.assertNotEquals(Null, dp.myclient);
        
        PageReference detp=Page.DetailsPage;
        test.setCurrentPage(detp);
        ApexPages.currentPage().getParameters().put('mycandidate', candidate.id);
        ApexPages.currentPage().getParameters().put('mysite', testc.id);
        ApexPages.currentPage().getParameters().put('myreg', r.id);
        ApexPages.currentPage().getParameters().put('myclient', a.id);
        
       //dp.setmyexam(myexam)
        dp=new DetailsPage();
        System.assertNotEquals(Null, dp.MytestCenter);

        System.assertNotEquals(Null, dp.getmyexam());
        System.assertNotEquals(Null, dp.getmyreg());
        
        System.assertNotEquals(Null, dp.mycandidate);
        System.assertNotEquals(Null, dp.myclient);
        dp.setmyexam(e);
        dp.setMyReg(r);
        dp.initData();
        dp.refreshVtsData();
    }
  
      


}