objects/Candidate__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Account is not a Client.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Candidates</relationshipLabel>
        <relationshipName>Candidates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VTS_Candidate_ID__c</fullName>
        <externalId>true</externalId>
        <label>VTS candidate ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Exam__c.object
<CustomObject>
    <fields>
        <fullName>Client__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Selected Account is not a Client.</errorMessage>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Client</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Exams</relationshipLabel>
        <relationshipName>Exams</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Exam</label>
    <nameField>
        <displayFormat>Exam - {00000}</displayFormat>
        <label>Exam ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Org_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>VTS_Reg_Data_Fresh_Life__c</fullName>
        <description>Time (in minutes) during which the VTS Reg data is considered fresh in Salesforce. After the interval has elapsed, data should be refreshed from VTS.</description>
        <inlineHelpText>Time (in minutes) during which the VTS Reg data is considered fresh in Salesforce.</inlineHelpText>
        <label>VTS Reg Data Fresh Life</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Org Settings</label>
</CustomObject>

objects/Registration__c.object
<CustomObject>
    <fields>
        <fullName>Candidate_Name__c</fullName>
        <formula>Candidate__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Candidate name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Candidate__c</fullName>
        <label>Candidate</label>
        <referenceTo>Candidate__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_and_Time_of_Exam__c</fullName>
        <label>Date and time of exam</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Exam__c</fullName>
        <label>Exam</label>
        <referenceTo>Exam__c</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Process_State_Code__c</fullName>
        <label>Process state code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Test center</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Registrations</relationshipLabel>
        <relationshipName>Registrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>VTS_Registration_ID__c</fullName>
        <externalId>true</externalId>
        <label>VTS Registration ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <label>Registration</label>
    <nameField>
        <displayFormat>R-{MM}-{00000}</displayFormat>
        <label>Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DetailsPage.cls
public with sharing class DetailsPage {

public Registration__c myreg {get;set;}
public Exam__c myexam {get;set;}

    public PageReference initData() {
        //refreshVtsData(false);
        new VTSPersistenceUtility().refreshVtsData(false, this.myreg, this.mycandidate, this.mytestCenter);
        this.myreg = null;
        this.mycandidate = null;
        this.mytestCenter = null;
        return null;
    }

    /*
    private void refreshVtsData(Boolean doForceRefresh) {

        //EsbDao dao = new DaoFactory().getEsbDao();
        VTSPersistenceUtility persistence = new VTSPersistenceUtility();
        VTS_Registration vtsReg;
        VTS_Candidate vtsCandidate;
        VTS_TestCenter vtsTestCenter;

        Decimal freshLife = Org_Settings__c.getInstance().VTS_Reg_Data_Fresh_Life__c;
        // If data is stale, fetch fresh data from VTS
        if ( doForceRefresh || (freshLife != null && this.myreg.LastModifiedDate.addMinutes(freshLife.intValue()) < System.now()) ) {
            try {
            	vtsReg = dao.getRegistrationByRegistrationId(this.myreg.VTS_Registration_ID__c.longValue());
            } catch(Exception e) {
                //Ignore b/c this is not a showstopper
                System.debug('ERROR getting registration data: ' + e);
            }
        }

        // If data is stale, fetch fresh data from VTS
        if ( doForceRefresh || (freshLife != null && this.mycandidate.LastModifiedDate.addMinutes(freshLife.intValue()) < System.now()) ) {
            try {
                vtsCandidate = dao.getCandidateByCandidateId(this.mycandidate.VTS_Candidate_ID__c.longValue());
            } catch(Exception e) {
                //Ignore b/c this is not a showstopper
                System.debug('ERROR getting Candidate data: ' + e);
            }
        }

        // If data is stale, fetch fresh data from VTS
        if ( doForceRefresh || (freshLife != null && this.MytestCenter.LastModifiedDate.addMinutes(freshLife.intValue()) < System.now()) ) {
            try {
                vtsTestCenter = dao.getTestCenterByTestCenterId(this.mytestCenter.VTS_Test_Center_ID__c.longValue());
            } catch(Exception e) {
                //Ignore b/c this is not a showstopper
                System.debug('ERROR getting Test Center data: ' + e);
            }
        }

        if ( vtsReg != null ) {
            // Update data returned from VTS
            persistence.upsertExam(vtsReg.exam, vtsReg.candidate.clientId);
            persistence.upsertRegistration(vtsReg);
            this.myreg = null;
        }
        
        if ( vtsCandidate != null ) {
            // Update data returned from VTS
            persistence.upsertCandidate(vtsCandidate);
            this.mycandidate = null;
        }
        
        if ( vtsTestCenter != null ) {
            // Update data returned from VTS
            persistence.upsertTestCenter(vtsTestCenter);
            this.mycandidate = null;
        }

    }
	*/

    public PageReference refreshVtsData() {

        /*
        EsbDao dao = new DaoFactory().getEsbDao();
        VTSPersistenceUtility persistence = new VTSPersistenceUtility();
        VTS_Registration vtsReg;
        VTS_Candidate vtsCandidate;
        VTS_TestCenter vtsTestCenter;

        try {
            vtsReg = dao.getRegistrationByRegistrationId(this.myreg.VTS_Registration_ID__c.longValue());
        } catch(Exception e) {
            //Ignore b/c this is not a showstopper
            System.debug('ERROR getting registration data: ' + e);
        }

        try {
            vtsCandidate = dao.getCandidateByCandidateId(this.mycandidate.VTS_Candidate_ID__c.longValue());
        } catch(Exception e) {
            //Ignore b/c this is not a showstopper
            System.debug('ERROR getting Candidate data: ' + e);
        }

        try {
            vtsTestCenter = dao.getTestCenterByTestCenterId(this.mytestCenter.VTS_Test_Center_ID__c.longValue());
        } catch(Exception e) {
            //Ignore b/c this is not a showstopper
            System.debug('ERROR getting Test Center data: ' + e);
        }

        if ( vtsReg != null ) {
            // Update data returned from VTS
            persistence.upsertExam(vtsReg.exam, vtsReg.candidate.clientId);
            persistence.upsertRegistration(vtsReg);
            this.myreg = null;
        }
        
        if ( vtsCandidate != null ) {
            // Update data returned from VTS
            persistence.upsertCandidate(vtsCandidate);
            this.mycandidate = null;
        }
        
        if ( vtsTestCenter != null ) {
            // Update data returned from VTS
            persistence.upsertTestCenter(vtsTestCenter);
            this.mycandidate = null;
        }
		*/

        new VTSPersistenceUtility().refreshVtsData(true, this.myreg, this.mycandidate, this.mytestCenter);
        this.myreg = null;
        this.mycandidate = null;
        this.mytestCenter = null;
        return null;
    }

public Candidate__c mycandidate {get
	{  mycandidate = new candidate__c();
		string candkey = '';
			if(myreg==null)
			{getmyreg();}
				if(myreg!=null)
					{candkey = string.valueof(myreg.get('Candidate__c'));}
					else { candkey = system.currentpagereference().getparameters().get('mycandidate');}	
					
				if(candkey != null && candkey != '')
					{
						string querystring = utility.Editablefields('Candidate__c');	
						string myquery = 'SELECT ' + querystring + ' FROM Candidate__c WHERE id = :candkey';
						try
							{
								mycandidate = database.query(myquery);
							}
						catch(system.queryexception candqe)
							{
								
							}	
					}
				return mycandidate;}					
				set;}



public Account MytestCenter {get
	{ 	mytestcenter = new account();
		string tckey = '';
			if(myreg==null)
			{getmyreg();}
				if(myreg!=null)
					{tckey = string.valueof(myreg.get('Test_Center__c'));}
				if(tckey=='' || tckey == null){tckey = system.currentpagereference().getparameters().get('mysite');}	
				system.debug('tckey'+tckey);
				if(tckey != null && tckey != '')
					{
						string querystring = utility.Editablefields('Account');	
                        if ( querystring.contains('BillingAddress') ) {
                            querystring = utility.Editablefields('Account');
                        }
						string myquery = 'SELECT ' + querystring + ' FROM Account WHERE id = :tckey';
				
						mytestCenter = database.query(myquery);
					}
					system.debug('mytestCenter=' + mytestcenter);
				return mytestCenter;}					
				set;}


public Account myclient{get
	{   myclient = new account();
		string clientkey = '';
			if(myexam==null)
			{getmyexam();}
				if(myexam!=null)
					{ clientkey = string.valueof(myexam.get('Client__c'));//--- invalid field
                    }
					else { clientkey = system.currentpagereference().getparameters().get('myclient');}	
						// { clientkey = system.currentpagereference().getparameters().get('myclient');}	
				if(clientkey != null && clientkey != '')
					{
						string querystring = utility.Editablefields('Account');	
						string myquery = 'SELECT ' + querystring + ' FROM Account WHERE id = :clientkey';
					
						try
							{
								myclient = database.query(myquery);
							}
						catch(system.queryexception clientqe)
							{
								
							}	
					}
				return myclient;}					
				set;}




public DetailsPage(){
	getmyreg();
}

public Registration__c getmyreg()
	{
	if (myreg==null && system.currentpagereference().getparameters().get('myreg')!=null)
		{	myreg = new registration__c();
			try{
                /*
				myreg = [SELECT Candidate__c, candidate__r.first_name__c, candidate__r.last_name__c, Candidate_name__c, Date_and_time_of_Exam__c, Exam__c,Exam__r.name, Process_state_code__c, Test_center__c, Test_center__r.name,VTS_Registration_id__c, id 
					  FROM Registration__c where Id = :system.currentpageReference().getparameters().get('myreg')];
				*/
                String regId = system.currentpageReference().getparameters().get('myreg');
                string querystring = utility.Editablefields('Registration__c');	
                string myquery = 'SELECT ' + querystring + ' FROM Registration__c WHERE id = :regId';
                myreg = Database.query(myquery);

				}
			catch(system.queryexception regqueryexception)
				{
					
				}	
		}
		else{myreg = myreg;}
		return myreg;
	}

Public Void setMyReg(Registration__c myreg)
	{
		this.myreg = myreg;
	}
		
public Exam__c getmyexam()
	{ myexam = new exam__c();
		string examkey = '';
	if(myreg==null)
	{getmyreg();}
		if(myreg!=null)
			{examkey = string.valueof(myreg.get('Exam__c'));}
			else { examkey = system.currentpagereference().getparameters().get('myexam');}	
		if(examkey != null && examkey != '')
		{
			string querystring = utility.Editablefields('Exam__c');	
			string myquery = 'SELECT ' + querystring + ' FROM Exam__c WHERE id = :examkey';
			try
				{
					myexam = database.query(myquery);	
				}
			catch( system.Queryexception examqe)
				{
					
				}
			
		}
		return myexam;
	}					

public void setmyexam(exam__c myexam){
		this.myexam = myexam;}


}